services:
  - type: web
    name: site-de-eventos
    env: native
    plan: free
    # Região do servidor mais próxima do Brasil para menor latência.
    region: ohio

    build_command: |
      # Comando para construir o projeto com Maven, pulando os testes para acelerar o deploy.
      ./mvnw package -DskipTests

    start_command: |
      # Comando para iniciar a aplicação Java após o build.
      # O nome do .jar deve ser o mesmo definido no seu pom.xml (<artifactId>-<version>.jar)
      java -jar target/site-de-eventos-0.0.1-SNAPSHOT.jar

    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SERVER_PORT
        value: 10000
      # Define a API Key do Google Maps. O valor será pego de um "Secret" no painel do Render.
      - key: GOOGLE_MAPS_API_KEY
        fromSecret: true
